module.exports = [
  {
    title: "Ail",
    url: "Ail",
    operation_culturale: "Plantation",
    semis: "Janvier - Avril",
    recolte: "Mai - Septembre",
    exposition: "Soleil",
  },
  {
    title: "Artichaut",
    url: "Artichaut",
    operation_culturale: "Plantation",
    semis: "Mars - Avril",
    recolte: "Mai - Octobre",
    exposition: "Soleil",
  },
  {
    title: "Asperge",
    url: "Asperge",
    operation_culturale: "Semis",
    semis: "Mars - Avril",
    recolte: "Avril - Juin",
    exposition: "Plein soleil",
  },
  {
    title: "Betterave",
    url: "Betterave",
    operation_culturale: "Semis",
    semis: "Mars - Juin",
    recolte: "Juillet - Octobre",
    exposition: "Plein soleil",
  },
  {
    title: "Brocoli",
    url: "Brocoli",
    operation_culturale: "Semis",
    semis: "Mai - Juin",
    recolte: "Septembre - Mars",
    exposition: "Soleil",
  },
  {
    title: "Carotte",
    url: "Carotte",
    operation_culturale: "Semis",
    semis: "Mars - Juillet",
    recolte: "Juillet - Novembre",
    exposition: "Plein soleil",
  },
  {
    title: "Chou-fleur",
    url: "ChouxFleur",
    operation_culturale: "Semis",
    semis: "Mai - Juillet",
    recolte: "Juin - Novembre",
    exposition: "Plein soleil",
  },
  {
    title: "Citrouille",
    url: "Citrouille",
    operation_culturale: "Semis",
    semis: "Mai - Juin",
    recolte: "Septembre - Décembre",
    exposition: "Plein soleil",
  },
  {
    title: "Concombre",
    url: "Concombre",
    operation_culturale: "Semis",
    semis: "Avril - Mai",
    recolte: "Juin - Août",
    exposition: "Plein soleil",
  },
  {
    title: "Courgette",
    url: "Courgette",
    operation_culturale: "Semis",
    semis: "Mars - Juillet",
    recolte: "Mai - Octobre",
    exposition: "Plein soleil",
  },
  {
    title: "Epinard",
    url: "Epinard",
    operation_culturale: "Semis",
    semis: "Février - Mai",
    recolte: "Octobre - Juillet",
    exposition: "Soleil / Ombre",
  },
  {
    title: "Oignon rouge",
    url: "OignonRouge",
    operation_culturale: "Semis",
    semis: "Février - Mai",
    recolte: "Mai - Novembre",
    exposition: "Soleil",
  },
  {
    title: "Panais",
    url: "Panais",
    operation_culturale: "Semis",
    semis: "Mars - Juin",
    recolte: "Septembre - Mars",
    exposition: "Plein soleil",
  },
  {
    title: "Patate",
    url: "Patate",
    operation_culturale: "Plantation",
    semis: "Mai - Juin",
    recolte: "Septembre - Octobre",
    exposition: "Soleil",
  },
  {
    title: "Petit pois",
    url: "PetitPois",
    operation_culturale: "Semis",
    semis: "Octobre - Mai",
    recolte: "Mars - Juillet",
    exposition: "Soleil / Mi-ombre",
  },
  {
    title: "Piment",
    url: "Piment",
    operation_culturale: "Semis",
    semis: "Février - Mai",
    recolte: "Juillet - Octobre",
    exposition: "Soleil",
  },
  {
    title: "Poivron",
    url: "Poivron",
    operation_culturale: "Semis",
    semis: "Février - Avril",
    recolte: "Juillet - Octobre",
    exposition: "Soleil",
  },
  {
    title: "Radis",
    url: "Radis",
    operation_culturale: "Semis",
    semis: "Janvier - Septembre",
    recolte: "Mars - Novembre",
    exposition: "Soleil / Mi-ombre",
  },
  {
    title: "Salade",
    url: "Salade",
    operation_culturale: "Semis",
    semis: "Février - Octobre",
    recolte: "Juin - Septembre",
    exposition: "Soleil",
  },
  {
    title: "Tomate",
    url: "Tomate",
    operation_culturale: "Semis",
    semis: "Février - Mai",
    recolte: "Juin - Octobre",
    exposition: "Soleil",
  },
];
