module.exports = [
  {
    title: "Ail",
    operation_culturale: "Plantation",
    semis: "Janvier - Avril",
    recolte: "Mai - Septembre",
    exposition: "Soleil",
  },
  {
    title: "Artichaut",
    operation_culturale: "Semis, Plantation",
    semis: "Mars - Avril",
    recolte: "Mai - Octobre, Septembre - Octobre",
    exposition: "Soleil",
  },
  {
    title: "Asperge",
    operation_culturale: "Semis",
    semis: "Mars - Avril",
    recolte: "Avril - Juin",
    exposition: "Plein soleil",
  },
  {
    title: "Betterave",
    operation_culturale: "Semis",
    semis: "Mars - Juin",
    recolte: "Juillet - Octobre",
    exposition: "Plein soleil",
  },
  {
    title: "Brocoli",
    operation_culturale: "Semis",
    semis: "Mai - Juin",
    recolte: "Septembre - Mars",
    exposition: "Soleil",
  },
  {
    title: "Carotte",
    operation_culturale: "Semis",
    semis: "Mars - Juillet",
    recolte: "Juillet - Novembre",
    exposition: "Plein soleil",
  },
  {
    title: "ChouxFleur",
    operation_culturale: "Semis",
    semis: "Mai - Juillet",
    recolte: "Juin - Novembre",
    exposition: "Plein soleil",
  },
  {
    title: "Citrouille",
    operation_culturale: "Semis",
    semis: "Mai - Juin",
    recolte: "Septembre - Décembre",
    exposition: "Plein soleil",
  },
  {
    title: "Concombre",
    operation_culturale: "Semis",
    semis: "Avril - Mai",
    recolte: "Juin - Août",
    exposition: "Plein soleil",
  },
  {
    title: "Courgette",
    operation_culturale: "Semis",
    semis: "Mars - Juillet",
    recolte: "Mai - Octobre",
    exposition: "Plein soleil",
  },
  {
    title: "Epinard",
    operation_culturale: "Semis",
    semis: "Février - Mai, Août - Novembre",
    recolte: "Octobre - Juillet",
    exposition: "Soleil / Ombre",
  },
  {
    title: "OignonRouge",
    operation_culturale: "Semis",
    semis: "Février - Mai, Août - Novembre",
    recolte: "Mai - Novembre",
    exposition: "Soleil",
  },
  {
    title: "Panais",
    operation_culturale: "Semis",
    semis: "Mars - Juin",
    recolte: "Septembre - Mars",
    exposition: "Plein soleil",
  },
  {
    title: "Patate",
    operation_culturale: "Plantation",
    semis: "Mai - Juin",
    recolte: "Septembre - Octobre",
    exposition: "Soleil",
  },
  {
    title: "PetitPois",
    operation_culturale: "Semis",
    semis: "Octobre - Mai",
    recolte: "Mars - Juillet",
    exposition: "Soleil / Mi-ombre",
  },
  {
    title: "Piment",
    operation_culturale: "Semis",
    semis: "Février - Mai",
    recolte: "Juillet - Octobre",
    exposition: "Soleil",
  },
  {
    title: "Poivron",
    operation_culturale: "Semis",
    semis: "Février - Avril",
    recolte: "Juillet - Octobre",
    exposition: "Soleil",
  },
  {
    title: "Radis",
    operation_culturale: "Semis",
    semis: "Janvier - Septembre",
    recolte: "Mars - Novembre",
    exposition: "Soleil / Mi-ombre",
  },
  {
    title: "Salade",
    operation_culturale: "Semis",
    semis: "Février - Octobre",
    recolte: "Juin - Septembre",
    exposition: "Soleil",
  },
  {
    title: "Tomate",
    operation_culturale: "Semis",
    semis: "Février - Mai",
    recolte: "Juin - Octobre",
    exposition: "Soleil",
  },
];
